import { useEffect, useMemo, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import { notifications } from "@mantine/notifications";
import { formatApiError } from "../../../../../shared/api/errors";
import { endpoints } from "../../../../../shared/api/endpoints";
import { http } from "../../../../../shared/api/http";
import { useCan } from "../../../../../shared/auth/useCan";
import { useMe } from "../../../../../shared/auth/useMe";
import {
  useAttendanceRecordsQuery,
  useGeneratePeriod,
  useLockPayrollPeriod,
  useMarkPayrollRunPaid,
  usePayrollPeriods,
  usePayrollRun,
  usePeriodRuns,
} from "../../../../../shared/hr/hooks";
import type { AttendanceRecord, PayrollRun, PayrollRunDetail } from "../../../../../shared/hr/hooks";
import type { PayrollUser } from "../types/payrollPeriodDetails.types";
import {
  buildRunSummary,
  calculatePayableTotal,
  formatUserName,
  getPeriodRange,
  parseAmount,
} from "../services/payrollPeriodDetails.utils.ts";

export function usePayrollPeriodDetailsData() {
  const params = useParams();
  const periodId = params.id ? Number(params.id) : null;

  const [search, setSearch] = useState("");
  const [selectedRun, setSelectedRun] = useState<PayrollRun | null>(null);
  const [hrName, setHrName] = useState("-");
  const [runPayables, setRunPayables] = useState<Record<number, number>>({});

  const runsQuery = usePeriodRuns(periodId);
  const periodsQuery = usePayrollPeriods();
  const runDetailsQuery = usePayrollRun(selectedRun?.id ?? null);
  const lockMutation = useLockPayrollPeriod(periodId);
  const generateMutation = useGeneratePeriod(periodId);
  const markPaidMutation = useMarkPayrollRunPaid();

  const canGenerate = useCan("hr.payroll.generate");
  const meQuery = useMe();
  const autoGeneratedRef = useRef(false);

  const runs = useMemo(() => runsQuery.data ?? [], [runsQuery.data]);
  const filteredRuns = useMemo(() => {
    if (!search) return runs;
    const term = search.toLowerCase();
    return runs.filter((run) => run.employee.full_name.toLowerCase().includes(term));
  }, [runs, search]);

  const periodStatus =
    periodsQuery.data?.find((period) => period.id === periodId)?.status ?? runDetailsQuery.data?.period?.status;

  const periodInfo =
    periodsQuery.data?.find((period) => period.id === periodId) ?? runDetailsQuery.data?.period ?? null;

  const periodRange = useMemo(() => (periodInfo ? getPeriodRange(periodInfo) : null), [periodInfo]);
  const runPeriodRange = useMemo(() => {
    return runDetailsQuery.data?.period ? getPeriodRange(runDetailsQuery.data.period) : null;
  }, [runDetailsQuery.data]);

  const attendanceQuery = useAttendanceRecordsQuery(
    {
      dateFrom: runPeriodRange?.dateFrom ?? undefined,
      dateTo: runPeriodRange?.dateTo ?? undefined,
      employeeId: runDetailsQuery.data?.employee.id ? String(runDetailsQuery.data.employee.id) : undefined,
    },
    Boolean(runDetailsQuery.data?.employee.id && runPeriodRange)
  );

  const runSummary = useMemo(
    () => buildRunSummary(runDetailsQuery.data, attendanceQuery.data ?? [], runPeriodRange),
    [attendanceQuery.data, runDetailsQuery.data, runPeriodRange]
  );

  const currentUserName = useMemo(() => {
    const user = meQuery.data?.user;
    if (!user) return "-";
    const fullName = `${user.first_name ?? ""} ${user.last_name ?? ""}`.trim();
    return fullName || user.username || "-";
  }, [meQuery.data?.user]);

  const roleNames = useMemo(() => {
    const currentRoles = meQuery.data?.roles ?? [];
    return currentRoles.map((role) => (role.slug || role.name).toLowerCase());
  }, [meQuery.data?.roles]);

  const isSuperUser = meQuery.data?.user.is_superuser ?? false;
  const managerName = roleNames.includes("manager") || isSuperUser ? currentUserName : "-";

  const payableTotal = useMemo(() => {
    if (runSummary) return calculatePayableTotal(runSummary);
    return runDetailsQuery.data?.net_total;
  }, [runDetailsQuery.data?.net_total, runSummary]);

  useEffect(() => {
    const currentPeriodRange = periodRange;
    if (!currentPeriodRange) return;

    const { dateFrom, dateTo } = currentPeriodRange;
    const missingRuns = runs.filter((run) => runPayables[run.id] == null);
    if (missingRuns.length === 0) return;

    let cancelled = false;

    async function loadPayables() {
      const results = await Promise.all(
        missingRuns.map(async (run) => {
          try {
            const [runDetailsResponse, attendanceResponse] = await Promise.all([
              http.get<PayrollRunDetail>(endpoints.hr.payrollRun(run.id)),
              http.get<AttendanceRecord[]>(endpoints.hr.attendanceRecords, {
                params: {
                  date_from: dateFrom,
                  date_to: dateTo,
                  employee_id: run.employee.id,
                },
              }),
            ]);

            const summary = buildRunSummary(runDetailsResponse.data, attendanceResponse.data ?? [], currentPeriodRange);
            const calculated = calculatePayableTotal(summary);

            return {
              id: run.id,
              payable: calculated ?? parseAmount(runDetailsResponse.data.net_total ?? run.net_total),
            };
          } catch {
            return { id: run.id, payable: parseAmount(run.net_total) };
          }
        })
      );

      if (cancelled) return;

      setRunPayables((prev) => {
        const next = { ...prev };
        results.forEach((result) => {
          next[result.id] = result.payable;
        });
        return next;
      });
    }

    loadPayables();
    return () => {
      cancelled = true;
    };
  }, [periodRange, runPayables, runs]);

  useEffect(() => {
    let cancelled = false;

    async function loadHrUser() {
      try {
        const response = await http.get<PayrollUser[]>(endpoints.users);
        const users = response.data ?? [];
        const hrUser = users.find((user) =>
          (user.roles ?? []).some((role) => (role.slug || role.name || "").toLowerCase() === "hr")
        );
        if (!cancelled) {
          setHrName(formatUserName(hrUser));
        }
      } catch {
        if (!cancelled) {
          setHrName("-");
        }
      }
    }

    loadHrUser();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    autoGeneratedRef.current = false;
  }, [periodId]);

  useEffect(() => {
    if (!periodId || autoGeneratedRef.current || !canGenerate) return;
    if (runsQuery.isLoading || runsQuery.isFetching) return;
    if ((runsQuery.data?.length ?? 0) > 0) return;
    if (periodStatus && periodStatus !== "draft") return;

    autoGeneratedRef.current = true;

    generateMutation
      .mutateAsync()
      .then(() => {
        notifications.show({
          title: "Payroll generated",
          message: "تم توليد الرواتب تلقائيًا.",
        });
        runsQuery.refetch();
      })
      .catch(() => {
        notifications.show({
          title: "Generate failed",
          message: "لم يتم توليد الرواتب تلقائيًا.",
          color: "red",
        });
      });
  }, [canGenerate, generateMutation, periodId, periodStatus, runsQuery]);

  const handleMarkPaid = async () => {
    if (!selectedRun?.id) return;
    try {
      await markPaidMutation.mutateAsync(selectedRun.id);
      notifications.show({
        title: "Payroll marked as paid",
        message: "تم تسجيل الراتب كمدفوع.",
      });
      runsQuery.refetch();
      runDetailsQuery.refetch();
    } catch {
      notifications.show({
        title: "Update failed",
        message: "تعذر تحديث حالة الراتب.",
        color: "red",
      });
    }
  };

  const fetchPayslipPngBlob = async (runId: number): Promise<Blob> => {
    const url = endpoints.hr.payrollRunPayslipPng(runId);
    const res = await http.get(url, {
      responseType: "blob",
      headers: { Accept: "image/png" },
      validateStatus: (s: number) => s >= 200 && s < 300,
    });
    const blob = res.data as Blob;
    const ct = (blob.type || String(res.headers["content-type"] || "")).toLowerCase();
    if (!ct.includes("image/png")) {
      const txt = await blob.text().catch(() => "");
      throw new Error(`Non-PNG response: ${ct}. ${txt.slice(0, 200)}`);
    }

    const headBuf = await blob.slice(0, 8).arrayBuffer();
    const sig = Array.from(new Uint8Array(headBuf));
    const pngSig = [137, 80, 78, 71, 13, 10, 26, 10];
    const ok = pngSig.every((b, idx) => sig[idx] === b);
    if (!ok) {
      const txt = await blob.text().catch(() => "");
      throw new Error(`Invalid PNG signature. ${txt.slice(0, 200)}`);
    }
    return blob;
  };

  const handleSavePng = async (runId: number) => {
    try {
      const blob = await fetchPayslipPngBlob(runId);
      const blobUrl = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = `payslip-${runId}.png`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.setTimeout(() => URL.revokeObjectURL(blobUrl), 1000);
    } catch (error) {
      console.error(error);
      notifications.show({
        title: "Save failed",
        message: "تعذر حفظ كشف المرتب.",
        color: "red",
      });
    }
  };

  const handleLockPeriod = async () => {
    if (!periodId) return;
    try {
      await lockMutation.mutateAsync();
      notifications.show({
        title: "Period locked",
        message: "تم قفل فترة الرواتب.",
      });
      runsQuery.refetch();
      runDetailsQuery.refetch();
    } catch (error) {
      notifications.show({
        title: "Lock failed",
        message: formatApiError(error) || "تعذر قفل الفترة.",
        color: "red",
      });
    }
  };

  return {
    search,
    setSearch,
    selectedRun,
    setSelectedRun,
    hrName,
    runPayables,
    runsQuery,
    periodsQuery,
    runDetailsQuery,
    lockMutation,
    markPaidMutation,
    meQuery,
    filteredRuns,
    periodStatus,
    periodInfo,
    runSummary,
    payableTotal,
    managerName,
    handleMarkPaid,
    handleSavePng,
    handleLockPeriod,
  };
}