import type { PayrollPeriod, SalaryType } from "../../../../shared/hr/hooks";
import type { FormState, HRActionsContent, Language } from "../types/hrActions.types";

export const contentMap: Record<Language, HRActionsContent> = {
  en: {
    brand: "managora",
    subtitle: "A smart dashboard that blends motion, clarity, and insight.",
    searchPlaceholder: "Search actions, employees, rules...",
    languageLabel: "Language",
    themeLabel: "Theme",
    navigationLabel: "Navigation",
    logoutLabel: "Logout",
    pageTitle: "HR Actions",
    pageSubtitle: "Track warnings and deductions across your workforce.",
    heroTag: "Last 30 days",
    stats: {
      total: "Total actions",
      warnings: "Warnings",
      deductions: "Deductions",
      period: "Active period",
    },
    table: {
      title: "Actions log",
      subtitle: "Latest employee actions and adjustments",
      employee: "Employee",
      rule: "Rule",
      action: "Action",
      value: "Value",
      reason: "Reason",
      period: "Period",
      manage: "Manage",
      edit: "Edit",
      emptyTitle: "No actions recorded yet",
      emptySubtitle: "New warnings and deductions will appear here.",
      loading: "Loading actions...",
    },
    modal: {
      title: "Edit action",
      actionType: "Action type",
      value: "Value",
      reason: "Reason",
      payrollPeriod: "Payroll period",
      noPeriods: "No payroll periods available",
      cancel: "Cancel",
      save: "Save changes",
    },
    actionTypes: {
      warning: "Warning",
      deduction: "Deduction",
    },
    userFallback: "Explorer",
    nav: {
      dashboard: "Dashboard",
      users: "Users",
      attendanceSelf: "My Attendance",
      leaveBalance: "Leave Balance",
      leaveRequest: "Leave Request",
      leaveMyRequests: "My Leave Requests",
      employees: "Employees",
      departments: "Departments",
      jobTitles: "Job Titles",
      hrAttendance: "HR Attendance",
      leaveInbox: "Leave Inbox",
      policies: "Policies",
      hrActions: "HR Actions",
      payroll: "Payroll",
      accountingSetup: "Accounting Setup",
      journalEntries: "Journal Entries",
      expenses: "Expenses",
      collections: "Collections",
      trialBalance: "Trial Balance",
      generalLedger: "General Ledger",
      profitLoss: "Profit & Loss",
      balanceSheet: "Balance Sheet",
      agingReport: "AR Aging",
      customers: "Customers",
      newCustomer: "New Customer",
      invoices: "Invoices",
      newInvoice: "New Invoice",
      catalog: "Products & Services",
      sales: "Sales",
      alertsCenter: "Alerts Center",
      cashForecast: "Cash Forecast",
      ceoDashboard: "CEO Dashboard",
      financeDashboard: "Finance Dashboard",
      hrDashboard: "HR Dashboard",
      auditLogs: "Audit Logs",
      setupTemplates: "Setup Templates",
      setupProgress: "Setup Progress",
    },
  },
  ar: {
    brand: "ماناجورا",
    subtitle: "لوحة ذكية تجمع الحركة والوضوح والرؤية التحليلية.",
    searchPlaceholder: "ابحث عن الإجراءات أو الموظفين أو القواعد...",
    languageLabel: "اللغة",
    themeLabel: "المظهر",
    navigationLabel: "التنقل",
    logoutLabel: "تسجيل الخروج",
    pageTitle: "إجراءات الموارد البشرية",
    pageSubtitle: "متابعة التنبيهات والخصومات عبر فريق العمل.",
    heroTag: "آخر ٣٠ يوم",
    stats: {
      total: "إجمالي الإجراءات",
      warnings: "تنبيهات",
      deductions: "خصومات",
      period: "الفترة الحالية",
    },
    table: {
      title: "سجل الإجراءات",
      subtitle: "أحدث الإجراءات والتعديلات للموظفين",
      employee: "الموظف",
      rule: "القاعدة",
      action: "الإجراء",
      value: "القيمة",
      reason: "السبب",
      period: "الفترة",
      manage: "إدارة",
      edit: "تعديل",
      emptyTitle: "لا توجد إجراءات حتى الآن",
      emptySubtitle: "ستظهر التنبيهات والخصومات الجديدة هنا.",
      loading: "جاري تحميل الإجراءات...",
    },
    modal: {
      title: "تعديل الإجراء",
      actionType: "نوع الإجراء",
      value: "القيمة",
      reason: "السبب",
      payrollPeriod: "فترة الراتب",
      noPeriods: "لا توجد فترات رواتب متاحة",
      cancel: "إلغاء",
      save: "حفظ التعديلات",
    },
    actionTypes: {
      warning: "تنبيه",
      deduction: "خصم",
    },
    userFallback: "ضيف",
    nav: {
      dashboard: "لوحة التحكم",
      users: "المستخدمون",
      attendanceSelf: "حضوري",
      leaveBalance: "رصيد الإجازات",
      leaveRequest: "طلب إجازة",
      leaveMyRequests: "طلباتي",
      employees: "الموظفون",
      departments: "الأقسام",
      jobTitles: "المسميات الوظيفية",
      hrAttendance: "حضور الموارد البشرية",
      leaveInbox: "وارد الإجازات",
      policies: "السياسات",
      hrActions: "إجراءات الموارد البشرية",
      payroll: "الرواتب",
      accountingSetup: "إعداد المحاسبة",
      journalEntries: "قيود اليومية",
      expenses: "المصروفات",
      collections: "التحصيلات",
      trialBalance: "ميزان المراجعة",
      generalLedger: "دفتر الأستاذ",
      profitLoss: "الأرباح والخسائر",
      balanceSheet: "الميزانية العمومية",
      agingReport: "أعمار الديون",
      customers: "العملاء",
      newCustomer: "عميل جديد",
      invoices: "الفواتير",
      newInvoice: "فاتورة جديدة",
      catalog: "الخدمات والمنتجات",
      sales: "المبيعات",
      alertsCenter: "مركز التنبيهات",
      cashForecast: "توقعات النقد",
      ceoDashboard: "لوحة CEO",
      financeDashboard: "لوحة المالية",
      hrDashboard: "لوحة الموارد البشرية",
      auditLogs: "سجل التدقيق",
      setupTemplates: "قوالب الإعداد",
      setupProgress: "تقدم الإعداد",
    },
  },
};

export const actionToneMap: Record<string, string> = {
  warning: "warning",
  deduction: "danger",
};

export const defaultFormState: FormState = {
  action_type: "warning",
  value: "",
  reason: "",
  payroll_period_id: "",
};

export const salaryPeriodMap: Record<SalaryType, PayrollPeriod["period_type"] | null> = {
  monthly: "monthly",
  weekly: "weekly",
  daily: "daily",
  commission: "monthly",
};

export function formatValue(value: string) {
  const num = Number(value);
  return Number.isNaN(num) ? value : num.toFixed(2);
}