import type { Language, LeaveBalancePageContent } from "../types/leaveBalance.types";

export const contentMap: Record<Language, LeaveBalancePageContent> = {
  en: {
    brand: "managora",
    welcome: "Welcome back",
    subtitle: "A smart dashboard that blends motion, clarity, and insight.",
    searchPlaceholder: "Search dashboards, teams, workflows...",
    languageLabel: "Language",
    themeLabel: "Theme",
    navigationLabel: "Navigation",
    logoutLabel: "Logout",
    pageTitle: "Leave Balance",
    pageSubtitle: "Track allocations, usage, and remaining days in one view.",
    userFallback: "Explorer",
    summaryTitle: "Balance summary",
    summarySubtitle: "Totals across all leave types",
    tableTitle: "Balance details",
    tableSubtitle: "Breakdown by leave type",
    tableHeaders: {
      type: "Leave type",
      year: "Year",
      allocated: "Allocated",
      used: "Used",
      remaining: "Remaining",
    },
    managerSectionTitle: "Team leave balances",
    managerSectionSubtitle:
      "Manage leave balances for employees in your company to avoid request errors.",
    managerFormTitle: "Add leave balance",
    managerFormSubtitle: "Assign a balance for a specific employee and leave type.",
    managerEmployeeLabel: "Employee",
    managerLeaveTypeLabel: "Leave type",
    managerYearLabel: "Year",
    managerAllocatedLabel: "Allocated days",
    managerSubmitLabel: "Add balance",
    managerEmployeesTitle: "Company employees",
    managerEmployeesSubtitle: "Select an employee to prefill the form.",
    managerEmployeeSearchPlaceholder: "Search employees...",
    managerSelectEmployeeLabel: "Select",
    managerEmployeeEmptyState: "No employees found yet.",
    managerSuccessMessage: "Leave balance added successfully.",
    managerErrorMessage: "Unable to add leave balance. Please review the details.",
    totals: {
      allocated: "Allocated balance",
      used: "Used balance",
      remaining: "Remaining balance",
    },    
    emptyState: "No leave balance recorded yet.",
    loadingLabel: "Loading...",
    nav: {
      dashboard: "Dashboard",
      users: "Users",
      attendanceSelf: "My Attendance",
      leaveBalance: "Leave Balance",
      leaveRequest: "Leave Request",
      leaveMyRequests: "My Leave Requests",
      employees: "Employees",
      departments: "Departments",
      jobTitles: "Job Titles",
      hrAttendance: "HR Attendance",
      leaveInbox: "Leave Inbox",
      policies: "Policies",
      hrActions: "HR Actions",
      payroll: "Payroll",
      accountingSetup: "Accounting Setup",
      journalEntries: "Journal Entries",
      expenses: "Expenses",
      collections: "Collections",
      trialBalance: "Trial Balance",
      generalLedger: "General Ledger",
      profitLoss: "Profit & Loss",
      balanceSheet: "Balance Sheet",
      agingReport: "AR Aging",
      customers: "Customers",
      newCustomer: "New Customer",
      invoices: "Invoices",
      newInvoice: "New Invoice",
      catalog: "Products & Services",
      sales: "Sales",
      alertsCenter: "Alerts Center",
      cashForecast: "Cash Forecast",
      ceoDashboard: "CEO Dashboard",
      financeDashboard: "Finance Dashboard",
      hrDashboard: "HR Dashboard",
      auditLogs: "Audit Logs",
      setupTemplates: "Setup Templates",
      setupProgress: "Setup Progress",
    },
  },
  ar: {
    brand: "ماناجورا",
    welcome: "أهلًا بعودتك",
    subtitle: "لوحة ذكية تجمع الحركة والوضوح والرؤية التحليلية.",
    searchPlaceholder: "ابحث عن اللوحات أو الفرق أو التدفقات...",
    languageLabel: "اللغة",
    themeLabel: "المظهر",
    navigationLabel: "التنقل",
    logoutLabel: "تسجيل الخروج",
    pageTitle: "رصيد الإجازات",
    pageSubtitle: "تابع المخصص والمستخدم والمتبقي في نظرة واحدة.",
    userFallback: "ضيف",
    summaryTitle: "ملخص الرصيد",
    summarySubtitle: "إجماليات كل الأنواع",
    tableTitle: "تفاصيل الرصيد",
    tableSubtitle: "التفاصيل حسب نوع الإجازة",
    tableHeaders: {
      type: "نوع الإجازة",
      year: "السنة",
      allocated: "المخصص",
      used: "المستخدم",
      remaining: "المتبقي",
    },
    managerSectionTitle: "أرصدة الإجازات للفريق",
    managerSectionSubtitle:
      "إدارة أرصدة الإجازات لموظفي الشركة لتجنب أخطاء طلب الإجازة.",
    managerFormTitle: "إضافة رصيد إجازات",
    managerFormSubtitle: "تعيين رصيد لموظف ونوع إجازة محدد.",
    managerEmployeeLabel: "الموظف",
    managerLeaveTypeLabel: "نوع الإجازة",
    managerYearLabel: "السنة",
    managerAllocatedLabel: "عدد الأيام المخصصة",
    managerSubmitLabel: "إضافة الرصيد",
    managerEmployeesTitle: "موظفو الشركة",
    managerEmployeesSubtitle: "اختر موظفًا لتعبئة النموذج تلقائيًا.",
    managerEmployeeSearchPlaceholder: "ابحث عن موظف...",
    managerSelectEmployeeLabel: "اختيار",
    managerEmployeeEmptyState: "لا يوجد موظفون حتى الآن.",
    managerSuccessMessage: "تمت إضافة رصيد الإجازات بنجاح.",
    managerErrorMessage: "تعذر إضافة رصيد الإجازات. تأكد من البيانات.",
    totals: {
      allocated: "الرصيد المخصص",
      used: "الرصيد المستخدم",
      remaining: "الرصيد المتبقي",
    },    
    emptyState: "لا يوجد رصيد مسجل بعد.",
    loadingLabel: "جاري التحميل...",
    nav: {
      dashboard: "لوحة التحكم",
      users: "المستخدمون",
      attendanceSelf: "حضوري",
      leaveBalance: "رصيد الإجازات",
      leaveRequest: "طلب إجازة",
      leaveMyRequests: "طلباتي",
      employees: "الموظفون",
      departments: "الأقسام",
      jobTitles: "المسميات الوظيفية",
      hrAttendance: "حضور الموارد البشرية",
      leaveInbox: "وارد الإجازات",
      policies: "السياسات",
      hrActions: "إجراءات الموارد البشرية",
      payroll: "الرواتب",
      accountingSetup: "إعداد المحاسبة",
      journalEntries: "قيود اليومية",
      expenses: "المصروفات",
      collections: "التحصيلات",
      trialBalance: "ميزان المراجعة",
      generalLedger: "دفتر الأستاذ",
      profitLoss: "الأرباح والخسائر",
      balanceSheet: "الميزانية العمومية",
      agingReport: "أعمار الديون",
      customers: "العملاء",
      newCustomer: "عميل جديد",
      invoices: "الفواتير",
      newInvoice: "فاتورة جديدة",
      catalog: "الخدمات والمنتجات",
      sales: "المبيعات",
      alertsCenter: "مركز التنبيهات",
      cashForecast: "توقعات النقد",
      ceoDashboard: "لوحة CEO",
      financeDashboard: "لوحة المالية",
      hrDashboard: "لوحة الموارد البشرية",
      auditLogs: "سجل التدقيق",
      setupTemplates: "قوالب الإعداد",
      setupProgress: "تقدم الإعداد",
    },
  },
};