# Generated by Django 5.2.12 on 2026-03-18 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auditlog_audit_comp_created_desc_idx"),
        ("hr", "0021_leavetype_requires_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance_comp_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance_comp_emp_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="leaverequest",
            name="leave_req_comp_status_idx",
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["company", "employee", "date"],
                include=("status", "check_in_time", "check_out_time"),
                name="attendance_comp_emp_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["company", "-date"],
                include=("employee", "status", "check_in_time"),
                name="attendance_comp_date_desc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["company", "status"],
                include=("start_date", "employee", "requested_at"),
                name="leave_req_comp_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["employee", "status", "start_date"],
                include=("end_date", "leave_type", "requested_at"),
                name="leave_req_emp_status_start_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                condition=models.Q(("is_deleted", False), ("status", "pending")),
                fields=["employee", "start_date"],
                include=("end_date", "leave_type", "requested_at"),
                name="leave_pending_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["payroll_run", "company"],
                include=("code", "type", "amount"),
                name="payline_run_comp_idx",
            ),
        ),
    ]