import type { JobTitlesContent, Language } from "../types/jobTitles.types";

export const jobTitlesContentMap: Record<Language, JobTitlesContent> = {
  en: {
    brand: "managora",
    subtitle: "A smart dashboard that blends motion, clarity, and insight.",
    searchPlaceholder: "Search job titles...",
    languageLabel: "Language",
    themeLabel: "Theme",
    navigationLabel: "Navigation",
    logoutLabel: "Logout",
    pageTitle: "Job Titles",
    pageSubtitle: "Manage active job titles across your organization.",
    addJobTitle: "Add Job Title",
    filtersTitle: "Job title filters",
    filtersSubtitle: "Refine by keyword or status",
    searchLabel: "Search",
    searchHint: "Search by job title name",
    statusLabel: "Status",
    statusPlaceholder: "All statuses",
    clearFilters: "Clear filters",
    stats: {
      total: "Total job titles",
      active: "Active",
      inactive: "Inactive",
    },
    table: {
      title: "Job titles list",
      subtitle: "Live status of all roles",
      name: "Name",
      status: "Status",
      actions: "Actions",
      edit: "Edit",
      delete: "Delete",
      emptyTitle: "No job titles found",
      emptySubtitle: "Try adjusting your search or add a new title.",
      loading: "Loading job titles...",
    },
    modal: {
      titleNew: "New Job Title",
      titleEdit: "Edit Job Title",
      nameLabel: "Job title name",
      namePlaceholder: "e.g. Senior Accountant",
      activeLabel: "Active",
      cancel: "Cancel",
      save: "Save",
    },
    statusMap: {
      active: "Active",
      inactive: "Inactive",
    },
    notifications: {
      createdTitle: "Job title created",
      createdMessage: "Job title created successfully.",
      updatedTitle: "Job title updated",
      updatedMessage: "Job title updated successfully.",
      deletedTitle: "Job title deleted",
      deletedMessage: "Job title deleted successfully.",
      errorTitle: "Something went wrong",
    },
    userFallback: "Explorer",
    nav: {
      dashboard: "Dashboard",
      users: "Users",
      attendanceSelf: "My Attendance",
      leaveBalance: "Leave Balance",
      leaveRequest: "Leave Request",
      leaveMyRequests: "My Leave Requests",
      employees: "Employees",
      departments: "Departments",
      jobTitles: "Job Titles",
      hrAttendance: "HR Attendance",
      leaveInbox: "Leave Inbox",
      policies: "Policies",
      hrActions: "HR Actions",
      payroll: "Payroll",
      accountingSetup: "Accounting Setup",
      journalEntries: "Journal Entries",
      expenses: "Expenses",
      collections: "Collections",
      trialBalance: "Trial Balance",
      generalLedger: "General Ledger",
      profitLoss: "Profit & Loss",
      balanceSheet: "Balance Sheet",
      agingReport: "AR Aging",
      customers: "Customers",
      newCustomer: "New Customer",
      invoices: "Invoices",
      newInvoice: "New Invoice",
      catalog: "Products & Services",
      sales: "Sales",
      alertsCenter: "Alerts Center",
      cashForecast: "Cash Forecast",
      ceoDashboard: "CEO Dashboard",
      financeDashboard: "Finance Dashboard",
      hrDashboard: "HR Dashboard",
      auditLogs: "Audit Logs",
      setupTemplates: "Setup Templates",
      setupProgress: "Setup Progress",
    },
  },
  ar: {
    brand: "ماناجورا",
    subtitle: "لوحة ذكية تجمع الحركة والوضوح والرؤية التحليلية.",
    searchPlaceholder: "ابحث عن المسميات الوظيفية...",
    languageLabel: "اللغة",
    themeLabel: "المظهر",
    navigationLabel: "التنقل",
    logoutLabel: "تسجيل الخروج",
    pageTitle: "المسميات الوظيفية",
    pageSubtitle: "إدارة المسميات النشطة داخل المنشأة.",
    addJobTitle: "إضافة مسمى وظيفي",
    filtersTitle: "فلاتر المسميات",
    filtersSubtitle: "قم بالتصفية بالكلمة أو الحالة",
    searchLabel: "بحث",
    searchHint: "ابحث باسم المسمى الوظيفي",
    statusLabel: "الحالة",
    statusPlaceholder: "كل الحالات",
    clearFilters: "مسح الفلاتر",
    stats: {
      total: "إجمالي المسميات",
      active: "نشطة",
      inactive: "غير نشطة",
    },
    table: {
      title: "قائمة المسميات الوظيفية",
      subtitle: "حالة كل مسمى بشكل مباشر",
      name: "المسمى",
      status: "الحالة",
      actions: "الإجراءات",
      edit: "تعديل",
      delete: "حذف",
      emptyTitle: "لا توجد مسميات",
      emptySubtitle: "جرّب إضافة مسمى جديد أو غيّر البحث.",
      loading: "جاري تحميل المسميات...",
    },
    modal: {
      titleNew: "مسمى وظيفي جديد",
      titleEdit: "تعديل مسمى وظيفي",
      nameLabel: "اسم المسمى الوظيفي",
      namePlaceholder: "مثال: محاسب أول",
      activeLabel: "نشط",
      cancel: "إلغاء",
      save: "حفظ",
    },
    statusMap: {
      active: "نشط",
      inactive: "غير نشط",
    },
    notifications: {
      createdTitle: "تم إنشاء المسمى",
      createdMessage: "تم إنشاء المسمى الوظيفي بنجاح.",
      updatedTitle: "تم تحديث المسمى",
      updatedMessage: "تم تحديث المسمى الوظيفي بنجاح.",
      deletedTitle: "تم حذف المسمى",
      deletedMessage: "تم حذف المسمى الوظيفي بنجاح.",
      errorTitle: "حدث خطأ",
    },
    userFallback: "ضيف",
    nav: {
      dashboard: "لوحة التحكم",
      users: "المستخدمون",
      attendanceSelf: "حضوري",
      leaveBalance: "رصيد الإجازات",
      leaveRequest: "طلب إجازة",
      leaveMyRequests: "طلباتي",
      employees: "الموظفون",
      departments: "الأقسام",
      jobTitles: "المسميات الوظيفية",
      hrAttendance: "حضور الموارد البشرية",
      leaveInbox: "وارد الإجازات",
      policies: "السياسات",
      hrActions: "إجراءات الموارد البشرية",
      payroll: "الرواتب",
      accountingSetup: "إعداد المحاسبة",
      journalEntries: "قيود اليومية",
      expenses: "المصروفات",
      collections: "التحصيلات",
      trialBalance: "ميزان المراجعة",
      generalLedger: "دفتر الأستاذ",
      profitLoss: "الأرباح والخسائر",
      balanceSheet: "الميزانية العمومية",
      agingReport: "أعمار الديون",
      customers: "العملاء",
      newCustomer: "عميل جديد",
      invoices: "الفواتير",
      newInvoice: "فاتورة جديدة",
      catalog: "الخدمات والمنتجات",
      sales: "المبيعات",
      alertsCenter: "مركز التنبيهات",
      cashForecast: "توقعات النقد",
      ceoDashboard: "لوحة CEO",
      financeDashboard: "لوحة المالية",
      hrDashboard: "لوحة الموارد البشرية",
      auditLogs: "سجل التدقيق",
      setupTemplates: "قوالب الإعداد",
      setupProgress: "تقدم الإعداد",
    },
  },
};