import type { Content, Language } from "../types/dashboard.types";

export const contentMap: Record<Language, Content> = {
  en: {
    brand: "managora",
    welcome: "Welcome back",
    subtitle: "A smart dashboard that blends motion, clarity, and insight.",
    searchPlaceholder: "Search dashboards, teams, workflows...",
    languageLabel: "Language",
    themeLabel: "Theme",
    navigationLabel: "Navigation",
    logoutLabel: "Logout",
    backupNowLabel: "Download backup",
    restoreBackupLabel: "Restore backup",
    dateFromLabel: "From",
    dateToLabel: "To",
    stats: {
      revenue: "Total revenue",
      expenses: "Total expenses",
      netProfit: "Estimated net profit",
    },
    activityTitle: "Smart Alerts",
    activitySubtitle: "Live KPI monitoring",
    insightsTitle: "Insight Pulse",
    insightsSubtitle: "Actual daily movement over the last week",
    forecastTitle: "Cashflow Snapshot",
    forecastSubtitle: "Forecasted inflows and outflows",
    commandCenterTitle: "Executive Command Center",
    commandCenterSubtitle:
      "Cross-functional KPIs generated from live finance, cash, HR, and risk engines",
    financeMixTitle: "Finance Mix",
    financeMixSubtitle: "Revenue vs expense vs net margin over the latest days",
    hrHealthTitle: "Workforce Health",
    hrHealthSubtitle: "Attendance quality and capacity pressure from HR signals",
    signalsTitle: "Risk Signals",
    signalsSubtitle: "Alert distribution by severity from the live alerts center",
    runwayLabel: "Cash runway",
    inflowLabel: "Inflow",
    outflowLabel: "Outflow",
    netExpectedLabel: "Net expected",
    overtimeLabel: "Overtime hours",
    absenceLabel: "Absence rate",
    latenessLabel: "Lateness rate",
    openAlertsLabel: "Open alerts",
    severityHigh: "High",
    severityMedium: "Medium",
    severityLow: "Low",
    noDataLabel: "No analytics data yet",
    generatedLabel: "Generated from system data",
    forecastLabels: {
      invoicesDue: "Invoices due",
      expectedCollected: "Expected collected",
      payroll: "Payroll",
      recurring: "Recurring expenses",
      topCustomer: "Top customer",
      topCategory: "Top category",
    },
    footer: "This system is produced by Creativity Code.",
    userFallback: "Explorer",
    searchResultsTitle: "Search results",
    searchResultsSubtitle: "Live data matched in your dashboard",
    searchEmptyTitle: "No results found",
    searchEmptySubtitle: "Try another keyword or check spelling.",
    loadingLabel: "Loading...",
    nav: {
      dashboard: "Dashboard",
      adminPanel: "Admin",
      users: "Users",
      attendanceSelf: "My Attendance",
      employeeSelfService: "Employee Self Service",
      messages: "Messages",
      leaveBalance: "Leave Balance",
      leaveRequest: "Leave Request",
      leaveMyRequests: "My Leave Requests",
      employees: "Employees",
      departments: "Departments",
      jobTitles: "Job Titles",
      hrAttendance: "HR Attendance",
      leaveInbox: "Leave Inbox",
      policies: "Policies",
      hrActions: "HR Actions",
      payroll: "Payroll",
      accountingSetup: "Accounting Setup",
      journalEntries: "Journal Entries",
      expenses: "Expenses",
      collections: "Collections",
      trialBalance: "Trial Balance",
      generalLedger: "General Ledger",
      profitLoss: "Profit & Loss",
      balanceSheet: "Balance Sheet",
      agingReport: "AR Aging",
      customers: "Customers",
      newCustomer: "New Customer",
      invoices: "Invoices",
      newInvoice: "New Invoice",
      alertsCenter: "Alerts Center",
      cashForecast: "Cash Forecast",
      ceoDashboard: "CEO Dashboard",
      financeDashboard: "Finance Dashboard",
      hrDashboard: "HR Dashboard",
      catalog: "Products & Services",
      auditLogs: "Audit Logs",
      setupTemplates: "Setup Templates",
      setupProgress: "Setup Progress",
    },
  },
  ar: {
    brand: "ماناجورا",
    welcome: "أهلًا بعودتك",
    subtitle: "لوحة ذكية تجمع الحركة والوضوح والرؤية التحليلية.",
    searchPlaceholder: "ابحث عن اللوحات أو الفرق أو التدفقات...",
    languageLabel: "اللغة",
    themeLabel: "المظهر",
    navigationLabel: "التنقل",
    logoutLabel: "تسجيل الخروج",
    backupNowLabel: "تحميل نسخة احتياطية",
    restoreBackupLabel: "استرجاع نسخة احتياطية",
    dateFromLabel: "من",
    dateToLabel: "إلى",
    stats: {
      revenue: "إجمالي الإيرادات",
      expenses: "إجمالي المصروفات",
      netProfit: "صافي الربح التقديري",
    },
    activityTitle: "تنبيهات ذكية",
    activitySubtitle: "مراقبة فورية للمؤشرات",
    insightsTitle: "نبض الرؤية",
    insightsSubtitle: "الحركة الفعلية لآخر أسبوع",
    forecastTitle: "ملخص التدفق النقدي",
    forecastSubtitle: "توقعات الدخول والخروج",
    commandCenterTitle: "مركز القيادة التنفيذي",
    commandCenterSubtitle:
      "مؤشرات مشتركة من النظام، ومتوسط الغياب مأخوذ من لوحة الموارد البشرية.",
    financeMixTitle: "مزيج المالية",
    financeMixSubtitle: "الإيراد مقابل المصروف مقابل هامش الربح خلال آخر الأيام",
    hrHealthTitle: "صحة القوى العاملة",
    hrHealthSubtitle: "جودة الحضور وضغط الطاقة التشغيلية من إشارات الموارد البشرية",
    signalsTitle: "إشارات المخاطر",
    signalsSubtitle: "توزيع التنبيهات حسب الشدة من مركز التنبيهات المباشر",
    runwayLabel: "مدى السيولة",
    inflowLabel: "التدفقات الداخلة",
    outflowLabel: "التدفقات الخارجة",
    netExpectedLabel: "الصافي المتوقع",
    overtimeLabel: "ساعات إضافية",
    absenceLabel: "متوسط الغياب",
    latenessLabel: "معدل التأخير",
    openAlertsLabel: "تنبيهات مفتوحة",
    severityHigh: "عالي",
    severityMedium: "متوسط",
    severityLow: "منخفض",
    noDataLabel: "لا توجد بيانات تحليلية بعد",
    generatedLabel: "مُولّد من بيانات النظام",
    forecastLabels: {
      invoicesDue: "فواتير مستحقة",
      expectedCollected: "تحصيل متوقع",
      payroll: "الرواتب",
      recurring: "مصروفات متكررة",
      topCustomer: "أعلى عميل",
      topCategory: "أعلى تصنيف",
    },
    footer: "هذا السيستم من انتاج كريتفيتي كود",
    userFallback: "ضيف",
    searchResultsTitle: "نتائج البحث",
    searchResultsSubtitle: "بيانات مباشرة مطابقة لكلماتك",
    searchEmptyTitle: "لا توجد نتائج",
    searchEmptySubtitle: "جرّب كلمة مختلفة أو تحقق من الإملاء.",
    loadingLabel: "جاري التحميل...",
    nav: {
      dashboard: "لوحة التحكم",
      adminPanel: "الإدارة",
      users: "المستخدمون",
      attendanceSelf: "حضوري",
      employeeSelfService: "الخدمات الذاتية للموظف",
      messages: "الرسائل",
      leaveBalance: "رصيد الإجازات",
      leaveRequest: "طلب إجازة",
      leaveMyRequests: "طلباتي",
      employees: "الموظفون",
      departments: "الأقسام",
      jobTitles: "المسميات الوظيفية",
      hrAttendance: "حضور الموارد البشرية",
      leaveInbox: "وارد الإجازات",
      policies: "السياسات",
      hrActions: "إجراءات الموارد البشرية",
      payroll: "الرواتب",
      accountingSetup: "إعداد المحاسبة",
      journalEntries: "قيود اليومية",
      expenses: "المصروفات",
      collections: "التحصيلات",
      trialBalance: "ميزان المراجعة",
      generalLedger: "دفتر الأستاذ",
      profitLoss: "الأرباح والخسائر",
      balanceSheet: "الميزانية العمومية",
      agingReport: "أعمار الديون",
      customers: "العملاء",
      newCustomer: "عميل جديد",
      invoices: "الفواتير",
      newInvoice: "فاتورة جديدة",
      alertsCenter: "مركز التنبيهات",
      cashForecast: "توقعات النقد",
      ceoDashboard: "لوحة CEO",
      financeDashboard: "لوحة المالية",
      hrDashboard: "لوحة الموارد البشرية",
      catalog: "الخدمات والمنتجات",
      auditLogs: "سجل التدقيق",
      setupTemplates: "قوالب الإعداد",
      setupProgress: "تقدم الإعداد",
    },
  },
};