import type { TemplateOption, Language, PoliciesContent } from "../types/policies.types";

export const contentMap: Record<Language, PoliciesContent> = {
  en: {
    brand: "managora",
    subtitle: "A smart dashboard that blends motion, clarity, and insight.",
    searchPlaceholder: "Search policies, rule types...",
    languageLabel: "Language",
    themeLabel: "Theme",
    navigationLabel: "Navigation",
    logoutLabel: "Logout",
    pageTitle: "Policies",
    pageSubtitle: "Define attendance rules and automate actions.",
    overviewLabel: "Policy rules",
    stats: {
      total: "Total rules",
      active: "Active rules",
      inactive: "Inactive rules",
      templates: "Templates used",
    },
    form: {
      title: "Create rule",
      subtitle: "Build a reusable policy template.",
      templateLabel: "Template",
      ruleNameLabel: "Rule name",
      ruleNamePlaceholder: "Enter rule name",
      thresholdLabel: "Threshold",
      periodLabel: "Period (days)",
      actionTypeLabel: "Action type",
      actionValueLabel: "Action value",
      actionWarning: "Warning",
      actionDeduction: "Deduction",
      activeLabel: "Activate rule",
      save: "Save rule",
    },
    table: {
      title: "Current rules",
      subtitle: "Live policy catalog",
      name: "Name",
      type: "Type",
      condition: "Condition",
      action: "Action",
      status: "Status",
      emptyTitle: "No rules yet",
      emptySubtitle: "Create your first policy above.",
      loading: "Loading rules...",
    },
    statusLabels: {
      active: "Active",
      inactive: "Inactive",
    },
    notifications: {
      missingTitle: "Missing data",
      missingMessage: "Choose a template and fill required values.",
      periodTitle: "Missing period",
      periodMessage: "Enter the period in days.",
      savedTitle: "Saved",
      savedMessage: "Policy rule created successfully.",
      errorTitle: "Save failed",
    },
    userFallback: "Explorer",
    nav: {
      dashboard: "Dashboard",
      users: "Users",
      attendanceSelf: "My Attendance",
      leaveBalance: "Leave Balance",
      leaveRequest: "Leave Request",
      leaveMyRequests: "My Leave Requests",
      employees: "Employees",
      departments: "Departments",
      jobTitles: "Job Titles",
      hrAttendance: "HR Attendance",
      leaveInbox: "Leave Inbox",
      policies: "Policies",
      hrActions: "HR Actions",
      payroll: "Payroll",
      accountingSetup: "Accounting Setup",
      journalEntries: "Journal Entries",
      expenses: "Expenses",
      collections: "Collections",
      trialBalance: "Trial Balance",
      generalLedger: "General Ledger",
      profitLoss: "Profit & Loss",
      balanceSheet: "Balance Sheet",
      agingReport: "AR Aging",
      customers: "Customers",
      newCustomer: "New Customer",
      invoices: "Invoices",
      newInvoice: "New Invoice",
      catalog: "Products & Services",
      sales: "Sales",
      alertsCenter: "Alerts Center",
      cashForecast: "Cash Forecast",
      ceoDashboard: "CEO Dashboard",
      financeDashboard: "Finance Dashboard",
      hrDashboard: "HR Dashboard",
      auditLogs: "Audit Logs",
      setupTemplates: "Setup Templates",
      setupProgress: "Setup Progress",
    },
  },
  ar: {
    brand: "ماناجورا",
    subtitle: "لوحة ذكية تجمع الحركة والوضوح والرؤية التحليلية.",
    searchPlaceholder: "ابحث عن سياسة أو نوع قاعدة...",
    languageLabel: "اللغة",
    themeLabel: "المظهر",
    navigationLabel: "التنقل",
    logoutLabel: "تسجيل الخروج",
    pageTitle: "السياسات",
    pageSubtitle: "عرّف قواعد الحضور تلقائيًا وإجراءات الجزاءات.",
    overviewLabel: "قواعد السياسات",
    stats: {
      total: "إجمالي القواعد",
      active: "قواعد فعالة",
      inactive: "قواعد غير فعالة",
      templates: "عدد القوالب",
    },
    form: {
      title: "إنشاء قاعدة",
      subtitle: "أنشئ قالب سياسة قابل لإعادة الاستخدام.",
      templateLabel: "القالب",
      ruleNameLabel: "اسم القاعدة",
      ruleNamePlaceholder: "أدخل اسم القاعدة",
      thresholdLabel: "الحد",
      periodLabel: "الفترة (أيام)",
      actionTypeLabel: "نوع الإجراء",
      actionValueLabel: "قيمة الإجراء",
      actionWarning: "تنبيه",
      actionDeduction: "خصم",
      activeLabel: "تفعيل القاعدة",
      save: "حفظ القاعدة",
    },
    table: {
      title: "القواعد الحالية",
      subtitle: "سجل السياسات المباشر",
      name: "الاسم",
      type: "النوع",
      condition: "الشرط",
      action: "الإجراء",
      status: "الحالة",
      emptyTitle: "لا توجد قواعد بعد",
      emptySubtitle: "ابدأ بإنشاء أول قاعدة أعلاه.",
      loading: "جاري تحميل القواعد...",
    },
    statusLabels: {
      active: "فعالة",
      inactive: "غير فعالة",
    },
    notifications: {
      missingTitle: "بيانات ناقصة",
      missingMessage: "اختر القالب وحدد القيم المطلوبة.",
      periodTitle: "مدة غير مكتملة",
      periodMessage: "يرجى إدخال عدد الأيام للفترة.",
      savedTitle: "تم الحفظ",
      savedMessage: "تم إنشاء القاعدة بنجاح.",
      errorTitle: "فشل الحفظ",
    },
    userFallback: "ضيف",
    nav: {
      dashboard: "لوحة التحكم",
      users: "المستخدمون",
      attendanceSelf: "حضوري",
      leaveBalance: "رصيد الإجازات",
      leaveRequest: "طلب إجازة",
      leaveMyRequests: "طلباتي",
      employees: "الموظفون",
      departments: "الأقسام",
      jobTitles: "المسميات الوظيفية",
      hrAttendance: "حضور الموارد البشرية",
      leaveInbox: "وارد الإجازات",
      policies: "السياسات",
      hrActions: "إجراءات الموارد البشرية",
      payroll: "الرواتب",
      accountingSetup: "إعداد المحاسبة",
      journalEntries: "قيود اليومية",
      expenses: "المصروفات",
      collections: "التحصيلات",
      trialBalance: "ميزان المراجعة",
      generalLedger: "دفتر الأستاذ",
      profitLoss: "الأرباح والخسائر",
      balanceSheet: "الميزانية العمومية",
      agingReport: "أعمار الديون",
      customers: "العملاء",
      newCustomer: "عميل جديد",
      invoices: "الفواتير",
      newInvoice: "فاتورة جديدة",
      catalog: "الخدمات والمنتجات",
      sales: "المبيعات",
      alertsCenter: "مركز التنبيهات",
      cashForecast: "توقعات النقد",
      ceoDashboard: "لوحة CEO",
      financeDashboard: "لوحة المالية",
      hrDashboard: "لوحة الموارد البشرية",
      auditLogs: "سجل التدقيق",
      setupTemplates: "قوالب الإعداد",
      setupProgress: "تقدم الإعداد",
    },
  },
};

export const templateOptions: TemplateOption[] = [
  {
    value: "late_over_minutes",
    label: "Late > X minutes → action",
    requiresPeriod: false,
  },
  {
    value: "late_count_over_period",
    label: "Late count > N خلال Y يوم → action",
    requiresPeriod: true,
  },
  {
    value: "absent_count_over_period",
    label: "Absent count > N خلال Y يوم → action",
    requiresPeriod: true,
  },
];