import type { Content, Language } from "../types/leaveInbox.types";

export const contentMap: Record<Language, Content> = {
  en: {
    brand: "managora",
    subtitle: "A smart dashboard that blends motion, clarity, and insight.",
    searchPlaceholder: "Search employees, leave types, statuses...",
    languageLabel: "Language",
    themeLabel: "Theme",
    navigationLabel: "Navigation",
    logoutLabel: "Logout",
    pageTitle: "Leave Inbox",
    pageSubtitle: "Review pending leave approvals and keep teams moving.",
    overviewLabel: "Pending approvals",
    stats: {
      pending: "Pending requests",
      totalDays: "Total days",
      averageDays: "Average duration",
      employees: "Employees impacted",
    },
    table: {
      title: "Approvals queue",
      subtitle: "Requests waiting for review",
      employee: "Employee",
      type: "Leave type",
      dates: "Dates",
      days: "Days",
      status: "Status",
      action: "Action",
      emptyTitle: "No pending requests",
      emptySubtitle: "All caught up for now.",
      loading: "Loading requests...",
      review: "Review",
    },
    reviewPanel: {
      title: "Request review",
      subtitle: "Approve or reject with notes.",
      emptyTitle: "Select a request",
      emptySubtitle: "Pick a row to review details.",
      employee: "Employee",
      type: "Leave type",
      dates: "Dates",
      days: "Days",
      reason: "Reason",
      rejectReasonLabel: "Rejection reason (optional)",
      rejectReasonPlaceholder: "Add an optional note...",
      approve: "Approve",
      reject: "Reject",
      pendingBadge: "Pending",
    },
    statusLabels: {
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      cancelled: "Cancelled",
    },
    notifications: {
      approveTitle: "Approved",
      approveMessage: "Leave request approved.",
      rejectTitle: "Rejected",
      rejectMessage: "Leave request rejected.",
      approveError: "Approval failed",
      rejectError: "Rejection failed",
    },
    userFallback: "Explorer",
    nav: {
      dashboard: "Dashboard",
      users: "Users",
      attendanceSelf: "My Attendance",
      leaveBalance: "Leave Balance",
      leaveRequest: "Leave Request",
      leaveMyRequests: "My Leave Requests",
      employees: "Employees",
      departments: "Departments",
      jobTitles: "Job Titles",
      hrAttendance: "HR Attendance",
      leaveInbox: "Leave Inbox",
      policies: "Policies",
      hrActions: "HR Actions",
      payroll: "Payroll",
      accountingSetup: "Accounting Setup",
      journalEntries: "Journal Entries",
      expenses: "Expenses",
      collections: "Collections",
      trialBalance: "Trial Balance",
      generalLedger: "General Ledger",
      profitLoss: "Profit & Loss",
      balanceSheet: "Balance Sheet",
      agingReport: "AR Aging",
      customers: "Customers",
      newCustomer: "New Customer",
      invoices: "Invoices",
      newInvoice: "New Invoice",
      catalog: "Products & Services",
      sales: "Sales",
      alertsCenter: "Alerts Center",
      cashForecast: "Cash Forecast",
      ceoDashboard: "CEO Dashboard",
      financeDashboard: "Finance Dashboard",
      hrDashboard: "HR Dashboard",
      auditLogs: "Audit Logs",
      setupTemplates: "Setup Templates",
      setupProgress: "Setup Progress",
    },
  },
  ar: {
    brand: "ماناجورا",
    subtitle: "لوحة ذكية تجمع الحركة والوضوح والرؤية التحليلية.",
    searchPlaceholder: "ابحث عن الموظف أو نوع الإجازة أو الحالة...",
    languageLabel: "اللغة",
    themeLabel: "المظهر",
    navigationLabel: "التنقل",
    logoutLabel: "تسجيل الخروج",
    pageTitle: "وارد الإجازات",
    pageSubtitle: "راجع طلبات الإجازة المعلقة وابقِ الفريق متحركًا.",
    overviewLabel: "طلبات معلقة",
    stats: {
      pending: "طلبات معلقة",
      totalDays: "إجمالي الأيام",
      averageDays: "متوسط المدة",
      employees: "عدد الموظفين",
    },
    table: {
      title: "قائمة المراجعة",
      subtitle: "طلبات بانتظار الاعتماد",
      employee: "الموظف",
      type: "نوع الإجازة",
      dates: "التواريخ",
      days: "الأيام",
      status: "الحالة",
      action: "إجراء",
      emptyTitle: "لا توجد طلبات معلقة",
      emptySubtitle: "تمت مراجعة كل الطلبات حتى الآن.",
      loading: "جاري تحميل الطلبات...",
      review: "مراجعة",
    },
    reviewPanel: {
      title: "مراجعة الطلب",
      subtitle: "وافق أو ارفض مع ملاحظات.",
      emptyTitle: "اختر طلبًا",
      emptySubtitle: "حدد طلبًا لعرض التفاصيل.",
      employee: "الموظف",
      type: "نوع الإجازة",
      dates: "التواريخ",
      days: "عدد الأيام",
      reason: "السبب",
      rejectReasonLabel: "سبب الرفض (اختياري)",
      rejectReasonPlaceholder: "أضف ملاحظة اختيارية...",
      approve: "موافقة",
      reject: "رفض",
      pendingBadge: "معلق",
    },
    statusLabels: {
      pending: "معلق",
      approved: "معتمد",
      rejected: "مرفوض",
      cancelled: "ملغي",
    },
    notifications: {
      approveTitle: "تمت الموافقة",
      approveMessage: "تم اعتماد الطلب.",
      rejectTitle: "تم الرفض",
      rejectMessage: "تم رفض الطلب.",
      approveError: "فشل الموافقة",
      rejectError: "فشل الرفض",
    },
    userFallback: "ضيف",
    nav: {
      dashboard: "لوحة التحكم",
      users: "المستخدمون",
      attendanceSelf: "حضوري",
      leaveBalance: "رصيد الإجازات",
      leaveRequest: "طلب إجازة",
      leaveMyRequests: "طلباتي",
      employees: "الموظفون",
      departments: "الأقسام",
      jobTitles: "المسميات الوظيفية",
      hrAttendance: "حضور الموارد البشرية",
      leaveInbox: "وارد الإجازات",
      policies: "السياسات",
      hrActions: "إجراءات الموارد البشرية",
      payroll: "الرواتب",
      accountingSetup: "إعداد المحاسبة",
      journalEntries: "قيود اليومية",
      expenses: "المصروفات",
      collections: "التحصيلات",
      trialBalance: "ميزان المراجعة",
      generalLedger: "دفتر الأستاذ",
      profitLoss: "الأرباح والخسائر",
      balanceSheet: "الميزانية العمومية",
      agingReport: "أعمار الديون",
      customers: "العملاء",
      newCustomer: "عميل جديد",
      invoices: "الفواتير",
      newInvoice: "فاتورة جديدة",
      catalog: "الخدمات والمنتجات",
      sales: "المبيعات",
      alertsCenter: "مركز التنبيهات",
      cashForecast: "توقعات النقد",
      ceoDashboard: "لوحة CEO",
      financeDashboard: "لوحة المالية",
      hrDashboard: "لوحة الموارد البشرية",
      auditLogs: "سجل التدقيق",
      setupTemplates: "قوالب الإعداد",
      setupProgress: "تقدم الإعداد",
    },
  },
};

export const statusClasses: Record<string, string> = {
  pending: "status-pill--pending",
  approved: "status-pill--approved",
  rejected: "status-pill--rejected",
  cancelled: "status-pill--cancelled",
};