import type { Content } from "../types/payrollPeriodDetails.types";

export const contentMap: Record<"en" | "ar", Content> = {
  en: {
    title: "Payroll Period Details",
    subtitle: "Review payroll runs, attendance, and payable totals.",
    periodLabel: "Period",
    statusLabel: "Status",
    searchLabel: "Search",
    searchPlaceholder: "Search by name",
    lockPeriod: "Lock period",
    locking: "Locking...",
    runsTitle: "Payroll runs",
    runsSubtitle: "Tap an employee to review payroll details.",
    loadingRuns: "Loading payroll runs...",
    emptyRuns: "No matching payroll runs.",
    table: {
      employee: "Employee",
      earnings: "Earnings total",
      deductions: "Deductions total",
      net: "Net",
      payable: "Payable total",
      actions: "Actions",
      view: "View details",
    },
    detailsTitle: "Run details",
    detailsSubtitle: "Payroll breakdown, attendance, and approvals.",
    closeDetails: "Hide details",
    loadingDetails: "Loading payroll details...",
    emptyDetails: "Select an employee to view details.",
    basic: "Basic",
    payableTotal: "Payable total",
    summary: {
      attendanceDays: "Attendance days",
      absenceDays: "Absence days",
      lateMinutes: "Late minutes",
      bonuses: "Bonuses",
      commissions: "Commissions",
      deductions: "Deductions",
      advances: "Advances",
    },
    linesTable: {
      line: "Line",
      type: "Type",
      amount: "Amount",
    },
    company: "Company",
    manager: "Manager",
    hr: "HR",
    markPaid: "Mark paid",
    markPaidDone: "Paid",
    savePng: "Save as PNG",
    status: {
      draft: "Draft",
      locked: "Locked",
      approved: "Approved",
      paid: "Paid",
    },
  },
  ar: {
    title: "تفاصيل فترة الرواتب",
    subtitle: "راجع الرواتب والحضور والإجمالي المستحق.",
    periodLabel: "الفترة",
    statusLabel: "الحالة",
    searchLabel: "بحث",
    searchPlaceholder: "ابحث بالاسم",
    lockPeriod: "قفل الفترة",
    locking: "جاري القفل...",
    runsTitle: "رواتب الفترة",
    runsSubtitle: "اختر موظفًا لعرض تفاصيل الراتب.",
    loadingRuns: "جاري تحميل الرواتب...",
    emptyRuns: "لا توجد رواتب مطابقة.",
    table: {
      employee: "الموظف",
      earnings: "إجمالي الاستحقاقات",
      deductions: "إجمالي الاستقطاعات",
      net: "الصافي",
      payable: "الإجمالي المستحق",
      actions: "الإجراءات",
      view: "عرض التفاصيل",
    },
    detailsTitle: "تفاصيل الراتب",
    detailsSubtitle: "تفاصيل الراتب والحضور والاعتمادات.",
    closeDetails: "إخفاء التفاصيل",
    loadingDetails: "جاري تحميل تفاصيل الراتب...",
    emptyDetails: "اختر موظفًا لعرض التفاصيل.",
    basic: "الأساسي",
    payableTotal: "الإجمالي المستحق",
    summary: {
      attendanceDays: "أيام الحضور",
      absenceDays: "أيام الغياب",
      lateMinutes: "دقائق التأخير",
      bonuses: "المكافآت",
      commissions: "العمولات",
      deductions: "الخصومات",
      advances: "السلف",
    },
    linesTable: {
      line: "البند",
      type: "النوع",
      amount: "المبلغ",
    },
    company: "الشركة",
    manager: "المدير",
    hr: "الموارد البشرية",
    markPaid: "تم الدفع",
    markPaidDone: "مدفوع",
    savePng: "حفظ كصورة",
    status: {
      draft: "مسودة",
      locked: "مقفلة",
      approved: "معتمدة",
      paid: "مدفوعة",
    },
  },
};