import type { Language, LeaveRequestContent } from "../types/leaveRequest.types";

export const contentMap: Record<Language, LeaveRequestContent> = {
  en: {
    brand: "managora",
    welcome: "Welcome back",
    subtitle: "A smart dashboard that blends motion, clarity, and insight.",
    searchPlaceholder: "Search dashboards, teams, workflows...",
    languageLabel: "Language",
    themeLabel: "Theme",
    navigationLabel: "Navigation",
    logoutLabel: "Logout",
    pageTitle: "Leave Request",
    pageSubtitle: "Submit a new leave request with confidence.",
    userFallback: "Explorer",
    formTitle: "Request details",
    formSubtitle: "Fill in the leave type, dates, and reasoning.",
    summaryTitle: "Request summary",
    summarySubtitle: "Preview how your request will appear.",
    fields: {
      leaveType: "Leave type",
      leaveTypePlaceholder: "Select a leave type",
      startDate: "Start date",
      endDate: "End date",
      daysLabel: "Calculated days",
      reason: "Reason",
      reasonPlaceholder: "Write your reason",
      notesLabel: "Notes",
    },
    actions: {
      submit: "Submit request",
    },
    notifications: {
      missingTitle: "Missing information",
      missingMessage: "Please select a leave type and dates.",
      successTitle: "Request sent",
      successMessage: "Your leave request was submitted successfully.",
      failedTitle: "Submission failed",
    },
    messages: {
      leaveTypesEmpty: "No leave types are available yet. Contact HR to set one up.",
      leaveTypesEmptyOption: "No leave types available",
      leaveTypesError: "Unable to load leave types. Please try again later.",
    },
    statusLabels: {
      pending: "Pending approval",
      draft: "Draft request",
    },
    nav: {
      dashboard: "Dashboard",
      users: "Users",
      attendanceSelf: "My Attendance",
      leaveBalance: "Leave Balance",
      leaveRequest: "Leave Request",
      leaveMyRequests: "My Leave Requests",
      employees: "Employees",
      departments: "Departments",
      jobTitles: "Job Titles",
      hrAttendance: "HR Attendance",
      leaveInbox: "Leave Inbox",
      policies: "Policies",
      hrActions: "HR Actions",
      payroll: "Payroll",
      accountingSetup: "Accounting Setup",
      journalEntries: "Journal Entries",
      expenses: "Expenses",
      collections: "Collections",
      trialBalance: "Trial Balance",
      generalLedger: "General Ledger",
      profitLoss: "Profit & Loss",
      balanceSheet: "Balance Sheet",
      agingReport: "AR Aging",
      customers: "Customers",
      newCustomer: "New Customer",
      invoices: "Invoices",
      newInvoice: "New Invoice",
      catalog: "Products & Services",
      sales: "Sales",
      alertsCenter: "Alerts Center",
      cashForecast: "Cash Forecast",
      ceoDashboard: "CEO Dashboard",
      financeDashboard: "Finance Dashboard",
      hrDashboard: "HR Dashboard",
      auditLogs: "Audit Logs",
      setupTemplates: "Setup Templates",
      setupProgress: "Setup Progress",
    },
  },
  ar: {
    brand: "ماناجورا",
    welcome: "أهلًا بعودتك",
    subtitle: "لوحة ذكية تجمع الحركة والوضوح والرؤية التحليلية.",
    searchPlaceholder: "ابحث عن اللوحات أو الفرق أو التدفقات...",
    languageLabel: "اللغة",
    themeLabel: "المظهر",
    navigationLabel: "التنقل",
    logoutLabel: "تسجيل الخروج",
    pageTitle: "طلب إجازة",
    pageSubtitle: "قدّم طلب إجازة جديد بكل سهولة.",
    userFallback: "ضيف",
    formTitle: "تفاصيل الطلب",
    formSubtitle: "أدخل نوع الإجازة والتواريخ وسبب الطلب.",
    summaryTitle: "ملخص الطلب",
    summarySubtitle: "معاينة قبل الإرسال.",
    fields: {
      leaveType: "نوع الإجازة",
      leaveTypePlaceholder: "اختر نوع الإجازة",
      startDate: "تاريخ البداية",
      endDate: "تاريخ النهاية",
      daysLabel: "عدد الأيام",
      reason: "سبب الطلب",
      reasonPlaceholder: "اكتب سبب الإجازة",
      notesLabel: "ملاحظات",
    },
    actions: {
      submit: "إرسال الطلب",
    },
    notifications: {
      missingTitle: "بيانات ناقصة",
      missingMessage: "يرجى اختيار نوع الإجازة وتحديد المدة.",
      successTitle: "تم الإرسال",
      successMessage: "تم إرسال طلب الإجازة بنجاح.",
      failedTitle: "فشل الإرسال",
    },
    messages: {
      leaveTypesEmpty: "لا توجد أنواع إجازات متاحة الآن. تواصل مع الموارد البشرية لإضافتها.",
      leaveTypesEmptyOption: "لا توجد أنواع إجازات متاحة",
      leaveTypesError: "تعذر تحميل أنواع الإجازات الآن. حاول لاحقًا.",
    },
    statusLabels: {
      pending: "بانتظار الموافقة",
      draft: "مسودة طلب",
    },
    nav: {
      dashboard: "لوحة التحكم",
      users: "المستخدمون",
      attendanceSelf: "حضوري",
      leaveBalance: "رصيد الإجازات",
      leaveRequest: "طلب إجازة",
      leaveMyRequests: "طلباتي",
      employees: "الموظفون",
      departments: "الأقسام",
      jobTitles: "المسميات الوظيفية",
      hrAttendance: "حضور الموارد البشرية",
      leaveInbox: "وارد الإجازات",
      policies: "السياسات",
      hrActions: "إجراءات الموارد البشرية",
      payroll: "الرواتب",
      accountingSetup: "إعداد المحاسبة",
      journalEntries: "قيود اليومية",
      expenses: "المصروفات",
      collections: "التحصيلات",
      trialBalance: "ميزان المراجعة",
      generalLedger: "دفتر الأستاذ",
      profitLoss: "الأرباح والخسائر",
      balanceSheet: "الميزانية العمومية",
      agingReport: "أعمار الديون",
      customers: "العملاء",
      newCustomer: "عميل جديد",
      invoices: "الفواتير",
      newInvoice: "فاتورة جديدة",
      catalog: "الخدمات والمنتجات",
      sales: "المبيعات",
      alertsCenter: "مركز التنبيهات",
      cashForecast: "توقعات النقد",
      ceoDashboard: "لوحة CEO",
      financeDashboard: "لوحة المالية",
      hrDashboard: "لوحة الموارد البشرية",
      auditLogs: "سجل التدقيق",
      setupTemplates: "قوالب الإعداد",
      setupProgress: "تقدم الإعداد",
    },
  },
};