# Generated by Django 5.2.12 on 2026-03-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_subscription_expires_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["company", "-created_at"],
                include=("actor", "action", "entity", "entity_id"),
                name="audit_comp_created_desc_idx",
            ),
        ),
    ]